# Makefile for the boot monitor package.

.include <bsd.own.mk>

# various boot blocks from NetBSD, ELF-compatible
SUBDIR+= mbr cdboot bootxx

# boot loader from NetBSD
SUBDIR+= boot

.include <bsd.subdir.mk>
