
INCSDIR=        /usr/include/minix

INCS+=	a.out.h bitmap.h callnr.h cdrom.h \
	com.h config.h const.h cpufeature.h \
	crtso.h debug.h devio.h dirent.h \
	dir.h dl_eth.h dmap.h driver.h \
	limits.h \
	drivers.h drvlib.h ds.h endpoint.h \
	fslib.h ioctl.h ipc.h ipcconst.h \
	keymap.h minlib.h mq.h \
	netdriver.h partition.h paths.h \
	portio.h priv.h profile.h queryparam.h \
	rs.h safecopies.h sched.h sef.h sound.h \
	spin.h sys_config.h sysinfo.h syslib.h \
	sysutil.h timers.h tty.h type.h types.h \
	u64.h vfsif.h vm.h vtreefs.h gcov.h  \
	compiler.h compiler-ack.h sha2.h sha1.h md5.h \
	audio_fw.h

.include <bsd.kinc.mk>
