#	MINIX-specific

.include <bsd.own.mk>

CONFIGFILES=	cp1251.fnt cp437.fnt cp850.fnt cp865.fnt cp866.fnt
CONFIGFILES+=	iso1.fnt koi8-r.fnt koi8-u.fnt polish.fnt
FILESDIR=	/usr/lib/fonts
FILES=		${NONBINMODE}

.include <bsd.prog.mk>
