.\" Written by Antoine Leca
.Dd January 21, 2013
.Dt UPDATE_BOOTCFG 8
.Os MINIX
.Sh NAME
.Nm update_bootcfg
.Nd Create or udpate the configuration for the boot monitor
.Sh SYNOPSIS
.Nm
.Op Fl dx
.Op Fl c Ar filename
.Op Fl t Ar default_cfg
.Op Fl l Ar local_cfg
.Op Fl r Ar rootdev
.Op Fl i Ar inherited_env
.Op Fl a Ar supps_args
.Op Fl B Ar basedir
.Op Fl D Ar minix_latest_dirname
.Op Ar destdir
.Sh DESCRIPTION
The
.Nm
command recreates the configuration file used by
MINIX boot monitor.
.Pp
The
.Fl c
option specifies the name of the updated file; the default value is
.Pa /boot.cfg .
The
.Fl t
and
.Fl l
options specify the names of the templates; the default values are
.Pa /etc/boot.cfg.default
and
.Pa /etc/boot.cfg.local
respectively; the former could be updated when the system changes,
while the latter holds the local modifications. The templates obey
the syntax for
.Xr boot.cfg 5 .
The
.Pa /etc/boot.cfg.default
template expects the system images to reside in the
.Pa /boot/minix
directory (can be overriden by the
.Fl B
option), and that
.Pa /boot/minix_latest
(unless overriden by the
.Fl D
option) points to last image, selected by the
.Em default=
command. Besides the directory to which points
.Pa /boot/minix_latest ,
all the directory entries within 
.Pa /boot/minix
are expected to be alternative system releases, and are given additional
.Em menu=
entries, with the basic parameters
.Em $rootdevname
and
.Em $args .
Template
.Em menu=
entries for inexistant directories, or directories without
.Pa kernel
file, are skipped; the
.Em default=
option is adjusted to point to the same relative menu entry.
.Pp
Within the templates, some variables can be used and will be
substituted by
.Nm
at run time. They are preceded by the dollar sign.
.Em $rootdevname
is replaced with the name of the device holding the (current)
root file system; this can be overriden with the
.Fl r
option.
.Em $args ,
which is intended to be at the end of the menu lines, is replaced
by the system environement values; unless overriden with the
.Fl i
option, the variables carried over are
.Em \"ahci acpi no_apic\" .
The
.Fl a
option allows to append
.Ar supps_args
as arbitrary options in addition to the inherited ones.
.Pp
Finally, the
.Nm
command updates the root file system, unless this is
changed by the
.Ar destdir
argument passed to the command. Note that the paths for
the template files
.Pa ( /etc/boot.cfg.default ,
.Pa /etc/boot.cfg.local )
are not affected by the value of
.Ar destdir .
.Sh FILES
.Bl -tag -width /etc/boot.cfg.default -compact
.It Pa /boot.cfg
Location of the configuration file; previous content of is lost
.It Pa /boot/minix/*
Directories with the various releases
.It Pa /boot/minix_default
Directory with the base release of MINIX, installed at
.Xr setup 8
time
.It Pa /boot/minix_latest
Symbolic link to the directory with the latest release, usually taken by default
.It Pa /etc/boot.cfg.default
Default template
.It Pa /etc/boot.cfg.local
Locally-defined additional boot commands
.El
.Sh BUGS
.Pp
The presence of
.Pa /boot/minix_latest
as a
.Em menu=
entry is not checked; it is assumed than one or several entries refer to it.
.Pp
The naming conventions, particularly the use of
.Em "default" ,
is not consistent.
.Sh SEE ALSO
.Xr boot 8 ,
.Xr boot.cfg 5 ,
.Xr setup 8 ,
.Xr sysenv 1